# Generated by Django 5.0.4 on 2024-05-07 08:53

import cloudwatch.validations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "alarm_id",
                    models.SmallAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "statistic",
                    models.CharField(
                        choices=[
                            ("SampleCount", "SAMPLE_COUNT"),
                            ("Sum", "SUM"),
                            ("Average", "AVERAGE"),
                            ("Minimum", "MINIMUM"),
                            ("Maximum", "MAXIMUM"),
                        ],
                        max_length=55,
                    ),
                ),
                ("threshold", models.PositiveSmallIntegerField()),
                (
                    "comparison_operator",
                    models.CharField(
                        choices=[
                            ("GreaterThanOrEqualToThreshold", "GREATER_THAN_OR_EQUAL"),
                            ("GreaterThanThreshold", "GREATER_THAN"),
                            ("LessThanThreshold", "LESS_THAN"),
                            ("LessThanOrEqualToThreshold", "LESS_THAN_OR_EQUAL"),
                            (
                                "LessThanLowerOrGreaterThanUpperThreshold",
                                "LESS_THAN_LOWER_OR_GREATER_THAN_UPPER",
                            ),
                            ("LessThanLowerThreshold", "LESS_THAN_LOWER"),
                            ("GreaterThanUpperThreshold", "GREATER_THAN_UPPER"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(help_text="In seconds ex: 5, 10"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metric_name", models.CharField(max_length=55)),
                (
                    "namespace",
                    models.CharField(
                        choices=[("AWS/Lambda", "Lambda"), ("AWS/EC2", "EC2")],
                        max_length=255,
                    ),
                ),
                (
                    "treat_missing_data",
                    models.CharField(
                        choices=[
                            ("breaching", "breaching"),
                            ("notBreaching", "notBreaching"),
                            ("ignore", "ignore"),
                            ("missing", "missing"),
                        ],
                        max_length=255,
                    ),
                ),
                ("evaluation_periods", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="AlertSource",
            fields=[
                (
                    "arn_id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "value",
                    models.CharField(
                        max_length=255,
                        validators=[cloudwatch.validations.ARNValidator()],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "dimension_id",
                    models.SmallAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("value", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlermDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alarm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimension",
                        to="cloudwatch.alarm",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cloudwatch.dimension",
                    ),
                ),
            ],
            options={
                "db_table": "cloudwatch_alarm_dimension",
            },
        ),
        migrations.CreateModel(
            name="AlarmAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("ALARM", "ALARM"),
                            ("INSUFFICIENT_DATA", "INSUFFICIENT_DATA"),
                        ],
                        default="OK",
                        max_length=55,
                    ),
                ),
                (
                    "alarm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cloudwatch.alarm",
                    ),
                ),
                (
                    "arn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cloudwatch.alertsource",
                    ),
                ),
            ],
            options={
                "db_table": "cloudwatch_alarm_action",
                "unique_together": {("alarm", "action", "arn")},
            },
        ),
    ]
