# Generated by Django 5.0.4 on 2024-05-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bugmanager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bugowner",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="bugmanager.developer"
            ),
        ),
    ]
